# Generated by Django 6.0.7 on 2026-08-04 07:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("user_icon", models.CharField(blank=True, default="", max_length=255)),
                ("user_name", models.CharField(max_length=100)),
                ("account_balance", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "db_table": "accounts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("account_balance__gte", 0)),
                        name="account_balance_gte_0",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transfer_amount",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_transactions",
                        to="api.account",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_transactions",
                        to="api.account",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("transfer_amount__gte", 1)),
                        name="transfer_amount_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("recipient")), _negated=True
                        ),
                        name="sender_recipient_different",
                    ),
                ],
            },
        ),
    ]
