# Generated by Django 6.0.7 on 2026-08-05 07:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "invoice_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_amount",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=200)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice_flag",
                    models.CharField(
                        choices=[("notpay", "未払い"), ("paid", "支払済み")],
                        default="notpay",
                        max_length=10,
                    ),
                ),
                ("paid_time", models.DateTimeField(blank=True, null=True)),
                (
                    "account_number",
                    models.ForeignKey(
                        db_column="account_number",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_invoices",
                        to="api.account",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="paid_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_invoices",
                        to="api.account",
                    ),
                ),
                (
                    "transaction_number",
                    models.OneToOneField(
                        blank=True,
                        db_column="transaction_number",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="api.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("invoice_amount__gte", 1)),
                        name="invoice_amount_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("invoice_flag__in", ["notpay", "paid"])),
                        name="invoice_flag_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("invoice_flag", "notpay"),
                                ("paid_by__isnull", True),
                                ("paid_time__isnull", True),
                                ("transaction_number__isnull", True),
                            ),
                            models.Q(
                                ("invoice_flag", "paid"),
                                ("paid_by__isnull", False),
                                ("paid_time__isnull", False),
                                ("transaction_number__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="invoice_payment_fields_match_flag",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("paid_by__isnull", True),
                            models.Q(
                                ("account_number", models.F("paid_by")), _negated=True
                            ),
                            _connector="OR",
                        ),
                        name="invoice_issuer_payer_different",
                    ),
                ],
            },
        ),
    ]
