# Generated by Django 6.0.7 on 2026-08-06 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_account_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="user",
            new_name="auth_user",
        ),
        migrations.AlterField(
            model_name="account",
            name="auth_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to=settings.AUTH_USER_MODEL,
                verbose_name="認証ユーザー",
            ),
        ),
    ]
